"""Which tool likely wrote this? Heuristic only — never a claim verdict."""

from __future__ import annotations

import re

# Order matters: first match wins.
TOOL_MARKERS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "cursor",
        (
            "cursor[bot]",
            "cursoragent",
            "generated by cursor",
            "generated with cursor",
            "co-authored-by: cursor",
            "cursor agent",
        ),
    ),
    (
        "claude",
        (
            "claude[bot]",
            "noreply@anthropic.com",
            "generated by claude",
            "generated with claude",
            "co-authored-by: claude",
            "claude code",
            "anthropic",
        ),
    ),
    (
        "copilot",
        (
            "copilot",
            "copilot-swe-agent",
            "copilot workspace",
            "co-authored-by: copilot",
            "made with copilot",
        ),
    ),
    (
        "codex",
        ("openai codex", "codex cli", "co-authored-by: codex"),
    ),
    (
        "devin",
        ("devin ai", "devin-ai", "cognition devin"),
    ),
    (
        "gemini",
        ("gemini cli", "google gemini", "gemini code assist"),
    ),
    (
        "aider",
        ("aider.chat", "co-authored-by: aider"),
    ),
    (
        "windsurf",
        ("windsurf", "codeium windsurf"),
    ),
    (
        "cline",
        ("cline.bot", "co-authored-by: cline"),
    ),
    (
        "generic_bot",
        ("[bot]", "dependabot", "renovate[bot]"),
    ),
)


def _blob(login: str | None, title: str | None, body: str | None) -> str:
    return " ".join(p for p in (login, title, body) if p).lower()


def detect_source(*, login: str | None = None, title: str | None = None, body: str | None = None) -> str | None:
    blob = _blob(login, title, body)
    if not blob.strip():
        return None
    for name, markers in TOOL_MARKERS:
        if any(m in blob for m in markers):
            return name
    return None


def likely_agent(*, login: str | None = None, title: str | None = None, body: str | None = None) -> bool:
    source = detect_source(login=login, title=title, body=body)
    return source is not None and source != "generic_bot"


def author_looks_agent(login: str | None) -> bool:
    return detect_source(login=login) is not None
